### 1 Add to Cart
POST http://localhost:3000/cart/add HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YWMzN2RmZTk4ZDZlNjc5MDc1ZmJmZTgiLCJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3OTExOTgwNzgsImV4cCI6MTc5MTE5ODk3OH0.YXFDsXbOk9m43dh63hCw6yi0q3Db2umnUudLaXRre14
Content-Type: application/json

{
  "productId": "4",
  "quantity": 1
}

### 2 Get Cart Items
GET http://localhost:3000/cart HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YWMzN2RmZTk4ZDZlNjc5MDc1ZmJmZTgiLCJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3OTExOTgwNzgsImV4cCI6MTc5MTE5ODk3OH0.YXFDsXbOk9m43dh63hCw6yi0q3Db2umnUudLaXRre14
### 3 Remove Item from Cart
DELETE http://localhost:3000/cart/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YWMzN2RmZTk4ZDZlNjc5MDc1ZmJmZTgiLCJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3OTExOTgwNzgsImV4cCI6MTc5MTE5ODk3OH0.YXFDsXbOk9m43dh63hCw6yi0q3Db2umnUudLaXRre14

### 4 get total price of cart items
GET http://localhost:3000/cart/total HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YWMzN2RmZTk4ZDZlNjc5MDc1ZmJmZTgiLCJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3OTExOTgwNzgsImV4cCI6MTc5MTE5ODk3OH0.YXFDsXbOk9m43dh63hCw6yi0q3Db2umnUudLaXRre14